### ISSUE TITLE
Redshift Destination

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#117]
We want to be able to read and write data from RedShift in bulk. Here are the steps to accomplish that:

## Step 1: Create new RedShift Destination interface

- [ ] Add a new package in [pkg/destinations](https://github.com/scratchdata/scratchdata/tree/main/pkg/destinations) called `redshift`
- [ ] Update [destinations.go](https://github.com/scratchdata/scratchdata/blob/main/pkg/destinations/destinations.go#L69-L74) to be able to connect to the new redshift destination.
- [ ] Implement the functions in the [Destination interface](https://github.com/scratchdata/scratchdata/blob/main/pkg/destinations/destinations.go#L20) for the new `redshift` package. For this first step, you may stub these functions (`panic("not implemented")`)

## Step 2: Implement Queries from RedShift

Set up configuration parameters for RedShift.

- [ ] The YAML configuration should look like this. If there are any fields that we need, then add them:

``` yaml
databases:
  - type: redshift
    api_keys:
      - test_api_key
    settings:
      delete_from_s3: true

      # Redshift connection
      redshift_host: myredshiftcluster.amazonaws.com 
      redshift_port: 5439 
      redshift_user: myuser 
      redshift_password: mypassword 
      redshift_dbname: mydb

      # S3 bucket
      s3_region: "us-east-1"
      s3_access_key_id: "ACCESS_KEY_ID"
      s3_secret_access_key: "SECRET_ACCESS_KEY"
      s3_bucket: "bucket_name"
```

- [ ] Implement `QueryJSON()` and `QueryCSV()` functions. This should execute the input query and output the result in the right format. You may find it useful to create a generic private `query()` function, and then have the JSON/CSV functions format data while returning. 
- [ ] Data should be streamed to the writer and avoid allocations as much as possible. Do not buffer all data into memory before returning to the client. Do not generate the entire JSON/CSV payload in memory.
- [ ] The `Close()` function should clean up the RedShift connection, and we should also close any open handlers related to executing the query.

## Step 3: Implement Table Creation 

Next, when the user inserts new data to big query, we want to create tables and columns based on the input data. Refer to the other packages in `pkg/destinations` for how to do this.

- [ ] Implement the `CreateEmptyTable()` function. This should create a table with the given name along with an int64 column called `__row_id`. You may use [this](https://github.com/scratchdata/scratchdata/blob/main/pkg/destinations/duckdb/insert.go#L73-L77) as a reference. This should only create the table if it doesn't already exist.
- [ ] Implement the `CreateColumns()` function. This should read the input file and alter the RedShift table to add columns if they do not exist. [Here](https://github.com/scratchdata/scratchdata/blob/main/pkg/destinations/duckdb/insert.go#L79) is a reference for how to do this.

## Implement Data Insertion

We want to bulk upload data to RedShift from the input file. This means implementing the `InsertFromNDJsonFile()` function. We will do this by uploading data to S3, loading from S3 to RedShift, and then optinally deleting the file from S3

- [ ] Data should be streamed to S3 in the location provided by s3. Do not load the data into memory when uploading .
- [ ] Insert data with the [COPY](https://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html) sql command. The input type is newline-delimited JSON.
- [ ] If the `delete_from_s3` flag is true, then delete the file from S3 if the copy command has been successful.
